package facturacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rainy
 */
import groovy.xml.Entity;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.ant.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.digester.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Toolkit;

public class InterfazReportes extends javax.swing.JFrame{

    /**
     * Creates new form InterfazReportes
     */
    private Connection connection = null;
    public InterfazReportes() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Daniel\\Desktop\\iconos\\grafico-de-informe-grafico-de-barras-icono-8104-48.png"));
    	setTitle("REPORTES");
    	getContentPane().setBackground(new Color(51, 153, 153));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton1.setForeground(Color.WHITE);
        jButton1.setBackground(Color.DARK_GRAY);
        jButton4 = new javax.swing.JButton();
        jButton4.setForeground(Color.WHITE);
        jButton4.setBackground(Color.DARK_GRAY);
        jButton5 = new javax.swing.JButton();
        jButton5.setForeground(Color.WHITE);
        jButton5.setBackground(Color.DARK_GRAY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Reporte Gastos Personales");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Reporte Gastos Personales por Mes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Detalles de facturas de gastos personales");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        
        JLabel lblEli = new JLabel("Seleccione el Tipo de Reporte que Desea Generar");
        lblEli.setForeground(Color.RED);
        lblEli.setFont(new Font("Rockwell Extra Bold", Font.BOLD, 15));
        
        JLabel label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\Users\\Daniel\\Desktop\\iconos\\verde-encuesta-icono-3749-48.png"));
        
        JLabel label_1 = new JLabel("");
        label_1.setIcon(new ImageIcon("C:\\Users\\Daniel\\Desktop\\iconos\\grafico-de-informe-grafico-de-barras-icono-8104-48.png"));
        
        JLabel label_2 = new JLabel("");
        label_2.setIcon(new ImageIcon("C:\\Users\\Daniel\\Desktop\\iconos\\informacion-del-informe-la-atencion-de-impresion-icono-6644-64.png"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        					.addGap(71)
        					.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(142)
        					.addComponent(lblEli, GroupLayout.PREFERRED_SIZE, 578, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(89, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(109)
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        			.addGap(321)
        			.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(260, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(246)
        			.addComponent(jButton5)
        			.addContainerGap(334, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(293)
        			.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblEli, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED))
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton4))
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addComponent(label_2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton5)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conexion conn= new conexion();
        connection=conn.conectado();
        JasperDesign jasperDesign;
	JasperReport jasperReport;
        JasperPrint jasperPrint;    
        String current = "";
        String usuario=Interfaz_Login.userloged.getUsuario();
        System.out.println(usuario);
        
        try {
            current = new java.io.File( "." ).getCanonicalPath();
            current+="\\src\\facturacion\\consultaGastosPersonales.jrxml";
            System.out.println("Current dir:"+current);
            HashMap parametros = new HashMap();
            parametros.put("cedula",usuario);
            JasperReport report = JasperCompileManager.compileReport(current);
            JasperPrint print = JasperFillManager.fillReport(report, parametros,connection);
            
 
            JasperViewer.viewReport(print);

        } catch (JRException ex) {
            Logger.getLogger(InterfazReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        conexion conn= new conexion();
        connection=conn.conectado();
        JasperDesign jasperDesign;
	JasperReport jasperReport;
        JasperPrint jasperPrint;    
        String current = "";
        String usuario=Interfaz_Login.userloged.getUsuario();
        System.out.println(usuario);
        
        try {
            current = new java.io.File( "." ).getCanonicalPath();
            current+="\\src\\facturacion\\consultaGastoPersonalMes.jrxml";
            System.out.println("Current dir:"+current);
            HashMap parametros = new HashMap();
            parametros.put("cedula",usuario);
            JasperReport report = JasperCompileManager.compileReport(current);
            JasperPrint print = JasperFillManager.fillReport(report, parametros,connection);
            
 
            JasperViewer.viewReport(print);

        } catch (JRException ex) {
            Logger.getLogger(InterfazReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new parametrosReporte3().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazReportes().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
}
